name: update-generated-files
description: git push if there is changed file(s)
inputs:
  committer-name:
    description: value for git config user.name
    required: true
    default: github-actions[bot]
  committer-email:
    description: value for git config user.email
    required: true
    default: 41898282+github-actions[bot]@users.noreply.github.com
  message:
    description: value for git commit --message
    required: true
    default: update-generated-files
  token:
    description: GitHub token to create a pull request
    required: true
    default: ${{ github.token }}
outputs:
  updated-sha:
    description: sha of a new commit if `git push` is done
    value: ${{ steps.run.outputs.updated-sha }}
runs:
  using: composite
  steps:
    - id: run
      shell: bash
      run: ${{ github.action_path }}/run.sh
      env:
        GIT_COMMITTER_NAME: ${{ inputs.committer-name }}
        GIT_COMMITTER_EMAIL: ${{ inputs.committer-email }}
        GIT_MESSAGE: ${{ inputs.message }}
        GITHUB_TOKEN: ${{ inputs.token }}
