name: update-generated-files
description: git push if there is changed file(s)

inputs:
  token:
    description: GitHub token to create a pull request
    required: true
    default: ${{ github.token }}

outputs:
  updated-sha:
    description: sha of a new commit if `git push` is done

runs:
  using: 'node16'
  main: 'dist/index.js'
