import { describe, expect, it, vi } from 'vitest'
import { failIfInfiniteLoopDetected } from '../src/commit.js'
import * as git from '../src/git.js'

vi.mock('../src/git')

describe('failIfInfiniteLoopDetected', () => {
  it('fails if the last commits are generated by this action', async () => {
    vi.mocked(git.getCommitMessages).mockResolvedValue([
      'Autofix 1\n\nGenerated-by: update-generated-files-action',
      'Autofix 2\n\nGenerated-by: update-generated-files-action',
      'Autofix 3\n\nGenerated-by: update-generated-files-action',
      'Autofix 4\n\nGenerated-by: update-generated-files-action',
      'Autofix 5\n\nGenerated-by: update-generated-files-action',
    ])
    await expect(failIfInfiniteLoopDetected('sha')).rejects.toThrow(/infinite loop/)
  })

  it('does not fail if the last commits has non-trailer messages', async () => {
    vi.mocked(git.getCommitMessages).mockResolvedValue([
      'Autofix 1\n\nGenerated-by: update-generated-files-action',
      'Autofix 2\n\nGenerated-by: update-generated-files-action',
      'Add feature',
      'Autofix 4\n\nGenerated-by: update-generated-files-action',
      'Autofix 5\n\nGenerated-by: update-generated-files-action',
    ])
    await failIfInfiniteLoopDetected('sha')
  })

  it('does not fail if the last commits are less than the limit', async () => {
    vi.mocked(git.getCommitMessages).mockResolvedValue([
      'Autofix 1\n\nGenerated-by: update-generated-files-action',
      'Autofix 2\n\nGenerated-by: update-generated-files-action',
    ])
    await failIfInfiniteLoopDetected('sha')
  })
})
