import { describe, expect, it, vi } from 'vitest'
import { hasConsecutiveAutoGeneratedCommits } from '../src/commit.js'
import * as git from '../src/git.js'

vi.mock('../src/git')

describe('hasConsecutiveAutoGeneratedCommits', () => {
  it('returns true if the last commits are generated by this action', async () => {
    vi.mocked(git.getCommitMessages).mockResolvedValue([
      'Autofix 1\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/101',
      'Autofix 2\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/102',
      'Autofix 3\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/103',
      'Autofix 4\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/104',
      'Autofix 5\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/105',
    ])
    expect(await hasConsecutiveAutoGeneratedCommits('sha')).toBe(true)
  })

  it('returns false if the last commits has non-trailer messages', async () => {
    vi.mocked(git.getCommitMessages).mockResolvedValue([
      'Autofix 1\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/101',
      'Autofix 2\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/102',
      'Add feature',
      'Autofix 4\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/104',
      'Autofix 5\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/105',
    ])
    expect(await hasConsecutiveAutoGeneratedCommits('sha')).toBe(false)
  })

  it('returns false if the last commits are less than the limit', async () => {
    vi.mocked(git.getCommitMessages).mockResolvedValue([
      'Autofix 1\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/101',
      'Autofix 2\n\nAuto-generated-by: update-generated-files-action; https://github.com/int128/update-generated-files-action/actions/runs/102',
    ])
    expect(await hasConsecutiveAutoGeneratedCommits('sha')).toBe(false)
  })
})
