import type { Octokit } from '@octokit/action'
import type { WebhookEvent } from '@octokit/webhooks-types'
import { expect, test, vi } from 'vitest'
import * as git from '../src/git.js'
import { handleOtherEvent } from '../src/other_event.js'

const octokitMock = {
  rest: {
    pulls: {
      create: vi.fn(),
      requestReviewers: vi.fn(),
    },
    issues: {
      addAssignees: vi.fn(),
      addLabels: vi.fn(),
    },
  },
}

vi.mock('@actions/core')
vi.mock('../src/git')

test('follow up by fast-forward', async () => {
  vi.mocked(git.getCommitMessages).mockResolvedValueOnce(['Commit message'])
  vi.mocked(git.push).mockResolvedValueOnce(0)

  const outputs = await handleOtherEvent(
    {
      commitMessage: 'Generated by GitHub Actions (workflow / job)',
      commitMessageFooter: 'https://github.com/int128/update-generated-files-action/actions/runs/4309709120',
      headBranch: 'update-generated-files--workflow--1--job--',
      title: 'Follow up the generated files',
      body: 'This pull request will fix the generated files.',
      draft: false,
      reviewers: ['myname', 'awesome/myteam'],
      labels: [],
      dryRun: false,
    },
    {
      ref: 'refs/heads/main',
      actor: 'octocat',
      eventName: 'dummy',
      sha: '0123456789abcdef',
      repo: {
        owner: 'int128',
        repo: 'update-generated-files-action',
      },
      payload: {} as WebhookEvent,
    },
    octokitMock as unknown as Octokit,
  )

  expect(outputs).toStrictEqual({})
  expect(git.commit).toHaveBeenCalledTimes(1)
  expect(git.commit).toHaveBeenCalledWith([
    `Generated by GitHub Actions (workflow / job)`,
    `https://github.com/int128/update-generated-files-action/actions/runs/4309709120`,
    `Generated-by: update-generated-files-action`,
  ])
  expect(git.push).toHaveBeenCalledTimes(1)
  expect(git.push).toHaveBeenCalledWith(
    {
      localRef: `HEAD`,
      remoteRef: 'refs/heads/main',
      dryRun: false,
    },
    {
      ignoreReturnCode: true,
    },
  )
})

test('fallback to pull-request', async () => {
  vi.mocked(git.getCommitMessages).mockResolvedValueOnce(['Commit message'])
  vi.mocked(git.push).mockResolvedValueOnce(1)
  vi.mocked(git.push).mockResolvedValueOnce(0)

  octokitMock.rest.pulls.create.mockResolvedValueOnce({
    data: {
      number: 987,
      html_url: 'https://github.com/int128/update-generated-files-action/pulls/987',
      base: {
        repo: {
          full_name: 'int128/update-generated-files-action',
        },
      },
    },
  })

  const outputs = await handleOtherEvent(
    {
      commitMessage: 'Generated by GitHub Actions (workflow / job)',
      commitMessageFooter: 'https://github.com/int128/update-generated-files-action/actions/runs/4309709120',
      headBranch: 'update-generated-files--workflow--1--job--0',
      title: 'Follow up the generated files',
      body: 'This pull request will fix the generated files.',
      draft: false,
      reviewers: ['myname', 'awesome/myteam'],
      labels: ['mylabel'],
      dryRun: false,
    },
    {
      ref: 'refs/heads/main',
      actor: 'octocat',
      eventName: 'dummy',
      sha: '0123456789abcdef',
      repo: {
        owner: 'int128',
        repo: 'update-generated-files-action',
      },
      payload: {} as WebhookEvent,
    },
    octokitMock as unknown as Octokit,
  )

  expect(outputs).toStrictEqual({
    error: undefined,
    pullRequestUrl: 'https://github.com/int128/update-generated-files-action/pulls/987',
    pullRequestNumber: 987,
  })
  expect(git.commit).toHaveBeenCalledTimes(1)
  expect(git.commit).toHaveBeenCalledWith([
    `Generated by GitHub Actions (workflow / job)`,
    `https://github.com/int128/update-generated-files-action/actions/runs/4309709120`,
    `Generated-by: update-generated-files-action`,
  ])
  expect(git.push).toHaveBeenCalledTimes(2)
  expect(git.push).toHaveBeenCalledWith(
    {
      localRef: `HEAD`,
      remoteRef: 'refs/heads/main',
      dryRun: false,
    },
    {
      ignoreReturnCode: true,
    },
  )
  expect(git.push).toHaveBeenCalledWith({
    localRef: `HEAD`,
    remoteRef: `refs/heads/update-generated-files--workflow--1--job--0`,
    dryRun: false,
  })

  expect(octokitMock.rest.pulls.create).toHaveBeenCalledWith({
    owner: 'int128',
    repo: 'update-generated-files-action',
    base: 'main',
    head: 'update-generated-files--workflow--1--job--0',
    draft: false,
    title: 'Follow up the generated files',
    body: `This pull request will fix the generated files.

----

Generated by GitHub Actions (workflow / job)
https://github.com/int128/update-generated-files-action/actions/runs/4309709120`,
  })
  expect(octokitMock.rest.pulls.requestReviewers).toHaveBeenCalledWith({
    owner: 'int128',
    pull_number: 987,
    repo: 'update-generated-files-action',
    reviewers: ['myname'],
    team_reviewers: ['myteam'],
  })
  expect(octokitMock.rest.issues.addLabels).toHaveBeenCalledWith({
    labels: ['mylabel'],
    issue_number: 987,
    owner: 'int128',
    repo: 'update-generated-files-action',
  })
})
