import * as git from '../src/git'
import { handlePullRequestEvent } from '../src/pull_request_event'

jest.mock('@actions/core')
jest.mock('../src/git')

test('pull request event', async () => {
  await handlePullRequestEvent(
    {
      title: 'Title',
      body: 'Body',
      token: 'GITHUB_TOKEN',
    },
    {
      ref: 'refs/pull/23/merge',
      workflow: 'workflow',
      job: 'job',
      runId: 123,
      serverUrl: 'https://github.com',
      repo: {
        owner: 'int128',
        repo: 'update-generated-files-action',
      },
      payload: {
        action: 'dummy',
        pull_request: {
          head: {
            ref: 'topic',
          },
        },
      },
    }
  )

  expect(git.fetchBranch).toHaveBeenCalledWith({
    ref: 'refs/pull/23/merge',
    token: 'GITHUB_TOKEN',
    depth: 2,
  })

  expect(git.updateBranch).toHaveBeenCalledWith({
    ref: 'refs/heads/topic',
    token: 'GITHUB_TOKEN',
    commitMessage:
      'Generated by GitHub Actions (workflow / job)\n\nhttps://github.com/int128/update-generated-files-action/actions/runs/123',
  })
})
