import * as core from '@actions/core'
import type { PullRequestEvent } from '@octokit/webhooks-types'
import { describe, expect, test, vi } from 'vitest'
import * as git from '../src/git.js'
import type { Context } from '../src/github.js'
import { handlePullRequestEvent } from '../src/pull_request_event.js'

vi.mock('@actions/core')
vi.mocked(core.info).mockImplementation(() => {})
vi.mock('../src/git')

describe('pull request event', () => {
  const inputs = {
    commitMessage: 'Generated by GitHub Actions (workflow / job)',
    commitMessageFooter: 'https://github.com/int128/update-generated-files-action/actions/runs/4309709120',
    token: 'GITHUB_TOKEN',
  }
  const context = {
    sha: '0123456789abcdef-merge',
    payload: {
      action: 'dummy',
      pull_request: {
        base: {
          ref: 'main',
        },
        head: {
          ref: 'topic',
          sha: '0123456789abcdef-head',
        },
      },
    },
  }

  test('checkout with merge commit', async () => {
    vi.mocked(git.getAuthorNameOfCommits).mockResolvedValue(['renovate[bot]'])
    vi.mocked(git.getCurrentSHA).mockResolvedValue('0123456789abcdef-merge')
    vi.mocked(git.canMerge).mockResolvedValueOnce(false)
    vi.mocked(git.canMerge).mockResolvedValueOnce(true)
    vi.mocked(git.getParentSHAs).mockResolvedValueOnce(['0123456789abcdef-latest-base', '0123456789abcdef-head'])

    await handlePullRequestEvent(inputs, context as Context<PullRequestEvent>)

    expect(git.stash).toHaveBeenCalledTimes(1)
    expect(git.checkout).toHaveBeenCalledWith('0123456789abcdef-head')
    expect(git.merge).toHaveBeenCalledWith(
      '0123456789abcdef-latest-base',
      `Merge branch main 0123456789abcdef-latest-base into topic 0123456789abcdef-head

Recreated a merge commit from 0123456789abcdef-merge by GitHub Actions
https://github.com/int128/update-generated-files-action/actions/runs/4309709120`,
    )
    expect(git.stashPop).toHaveBeenCalledTimes(1)
    expect(git.commit).toHaveBeenCalledWith(`Generated by GitHub Actions (workflow / job)

https://github.com/int128/update-generated-files-action/actions/runs/4309709120`)
    expect(git.push).toHaveBeenCalledTimes(1)
  })

  test('checkout with head commit', async () => {
    vi.mocked(git.getAuthorNameOfCommits).mockResolvedValue(['renovate[bot]'])
    vi.mocked(git.getCurrentSHA).mockResolvedValue('0123456789abcdef-head')
    await handlePullRequestEvent(inputs, context as Context<PullRequestEvent>)

    expect(git.checkout).not.toHaveBeenCalled()
    expect(git.merge).not.toHaveBeenCalled()
    expect(git.commit).toHaveBeenCalledWith(`Generated by GitHub Actions (workflow / job)

https://github.com/int128/update-generated-files-action/actions/runs/4309709120`)
    expect(git.push).toHaveBeenCalledTimes(1)
  })

  test('last authors are this action', async () => {
    vi.mocked(git.getAuthorNameOfCommits).mockResolvedValue([
      git.AUTHOR_NAME,
      git.AUTHOR_NAME,
      git.AUTHOR_NAME,
      git.AUTHOR_NAME,
      git.AUTHOR_NAME,
    ])
    await expect(handlePullRequestEvent(inputs, context as Context<PullRequestEvent>)).rejects.toThrow(/infinite loop/)
  })
})
