import * as core from '@actions/core'
import * as git from './git.js'
import type { Context } from './github.js'

const LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS = 5

export const getAutoGeneratedTrailer = (context: Context) =>
  `Auto-generated-by: update-generated-files-action; ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`

export const hasConsecutiveAutoGeneratedCommits = async (headSHA: string, context: Context) =>
  await core.group(
    `Checking the last ${LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS} commits to prevent an infinite loop`,
    async () => {
      await git.fetch({ refs: [headSHA], depth: LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS }, context)
      const lastCommitMessages = await git.getCommitMessages(headSHA, LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS)
      return (
        lastCommitMessages.length === LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS &&
        lastCommitMessages.every((message) => /^Auto-generated-by: update-generated-files-action;/m.test(message))
      )
    },
  )
