import * as core from '@actions/core'
import * as git from './git.js'
import type { Context } from './github.js'

const LIMIT_REPEATED_COMMITS = 5

const AUTO_GENERATED_TRAILER = 'Auto-generated-by: update-generated-files-action'

export const getAutoGeneratedTrailer = (context: Context) =>
  `${AUTO_GENERATED_TRAILER}; ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`

export const detectRepeatedCommits = async (headSHA: string) =>
  await core.group(`Checking the last ${LIMIT_REPEATED_COMMITS} commits to detect an infinite loop`, async () => {
    await git.fetch({ refs: [headSHA], depth: LIMIT_REPEATED_COMMITS })
    const lastCommitMessages = await git.getCommitMessages(headSHA, LIMIT_REPEATED_COMMITS)
    return (
      lastCommitMessages.length === LIMIT_REPEATED_COMMITS &&
      lastCommitMessages.every((message) => message.includes(AUTO_GENERATED_TRAILER))
    )
  })
