import * as core from '@actions/core'
import type { Octokit } from '@octokit/action'
import * as git from './git.js'
import type { Context } from './github.js'

const LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS = 5

export const getAutoGeneratedTrailer = (context: Context) =>
  `Auto-generated-by: update-generated-files-action; ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`

export const hasConsecutiveAutoGeneratedCommits = async (headSHA: string, context: Context) =>
  await core.group(
    `Checking the last ${LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS} commits to prevent an infinite loop`,
    async () => {
      await git.fetch({ refs: [headSHA], depth: LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS }, context)
      const lastCommitMessages = await git.getCommitMessages(headSHA, LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS)
      return (
        lastCommitMessages.length === LIMIT_CONSECUTIVE_AUTO_GENERATED_COMMITS &&
        lastCommitMessages.every((message) => /^Auto-generated-by: update-generated-files-action;/m.test(message))
      )
    },
  )

export const signCurrentCommit = async (context: Context, octokit: Octokit) => {
  const unsignedCommitSHA = await git.getCurrentSHA()
  await git.showGraph()
  const signingBranch = `signing--${unsignedCommitSHA}`
  await git.push({ localRef: unsignedCommitSHA, remoteRef: `refs/heads/${signingBranch}`, dryRun: false }, context)
  try {
    const { data: unsignedCommit } = await octokit.rest.git.getCommit({
      owner: context.repo.owner,
      repo: context.repo.repo,
      commit_sha: unsignedCommitSHA,
    })
    const { data: signedCommit } = await octokit.rest.git.createCommit({
      owner: context.repo.owner,
      repo: context.repo.repo,
      message: unsignedCommit.message,
      tree: unsignedCommit.tree.sha,
      parents: unsignedCommit.parents.map((parent) => parent.sha),
    })
    await octokit.rest.git.updateRef({
      owner: context.repo.owner,
      repo: context.repo.repo,
      ref: `heads/${signingBranch}`,
      sha: signedCommit.sha,
      force: true,
    })
    await git.showGraph()
    await git.fetch({ refs: [signedCommit.sha], depth: 1 }, context)
    await git.showGraph()
    await git.checkout(signedCommit.sha)
    await git.showGraph()
  } finally {
    await git.deleteRef(`refs/heads/${signingBranch}`, context)
  }
}
