import * as core from '@actions/core'
import * as git from './git'
import { Inputs } from './run'
import { Context } from '@actions/github/lib/context'
import { WebhookPayload } from '@actions/github/lib/interfaces'

export type PullRequestContext = Pick<Context, 'ref' | 'workflow' | 'job' | 'runId' | 'serverUrl' | 'repo'> & {
  payload: Pick<WebhookPayload, 'action'> & {
    pull_request?: {
      head: {
        ref: string
      }
    }
  }
}

export const handlePullRequestEvent = async (inputs: Inputs, context: PullRequestContext) => {
  if (context.payload.pull_request === undefined) {
    throw new Error(`context.payload.pull_request is undefined`)
  }
  const head = context.payload.pull_request.head.ref

  core.info(`Updating the head branch ${head}`)
  await git.fetchBranch({ ref: context.ref, depth: 2, token: inputs.token })
  await git.updateBranch({ ref: `refs/heads/${head}`, commitMessage: commitMessage(context), token: inputs.token })

  core.summary.addHeading('Automatically updated the pull request')
  core.summary.addRaw(`GitHub Actions added a commit to the head branch ${head}.`)
  await core.summary.write()

  if (context.payload.action === 'opened' || context.payload.action === 'synchronize') {
    // fail if the head ref is outdated
    throw new Error(`GitHub Actions added a commit to the pull request. Check the status of the new commit.`)
  }
  return
}

const commitMessage = (
  context: PullRequestContext
) => `Generated by GitHub Actions (${context.workflow} / ${context.job})

${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
