import assert from 'node:assert'
import * as core from '@actions/core'
import type { PullRequestEvent } from '@octokit/webhooks-types'
import { getAutoGeneratedTrailer, hasConsecutiveAutoGeneratedCommits } from './commit.js'
import * as git from './git.js'
import type { Context } from './github.js'
import type { Outputs } from './run.js'

export type Inputs = {
  commitMessage: string
  commitMessageFooter: string
  dryRun: boolean
}

export const handlePullRequestEvent = async (inputs: Inputs, context: Context<PullRequestEvent>): Promise<Outputs> => {
  if (await hasConsecutiveAutoGeneratedCommits(context.payload.pull_request.head.sha, context)) {
    throw new Error(`Detected consecutive auto-generated commits. Stopped execution to prevent an infinite loop.`)
  }

  const currentCommitIsMergeCommit = (await git.getCurrentSHA()) === context.sha
  if (currentCommitIsMergeCommit) {
    await cherryPickWorkspaceChangesOntoHead(inputs, context)
  } else {
    core.info(`Committing the workspace changes on the head branch directly`)
    await git.commit([inputs.commitMessage, inputs.commitMessageFooter, getAutoGeneratedTrailer(context)])
  }
  await git.showGraph()

  const headRef = context.payload.pull_request.head.ref
  core.info(`Updating the head branch ${headRef}`)
  await git.push({ localRef: `HEAD`, remoteRef: `refs/heads/${headRef}`, dryRun: inputs.dryRun }, context)

  if (context.payload.action === 'opened' || context.payload.action === 'synchronize') {
    core.summary.addRaw(`Added a commit. CI should pass on the new commit.`)
    await core.summary.write()
    if (inputs.dryRun) {
      core.warning(`[dry-run] Added a commit. CI should pass on the new commit.`)
      return {}
    }
    // Intentionally fail the CI to prevent auto-merging the PR with the broken commit.
    // The new commit will trigger a new CI, and the PR will be auto-merged if the new CI passes.
    throw new Error(`Added a commit. CI should pass on the new commit.`)
  }
  return {}
}

const cherryPickWorkspaceChangesOntoHead = async (inputs: Inputs, context: Context<PullRequestEvent>) => {
  core.info(`Committing the workspace changes`)
  await git.commit([inputs.commitMessage, inputs.commitMessageFooter, getAutoGeneratedTrailer(context)])
  const workspaceChangeSHA = await git.getCurrentSHA()

  core.info(`Fetching commits between the base and head branches to ensure we can cherry-pick onto the head branch`)
  const parentSHAs = await git.getParentSHAs(context.sha)
  const headSHA = context.payload.pull_request.head.sha
  const baseSHA = parentSHAs.filter((sha) => sha !== headSHA).pop()
  assert(baseSHA !== undefined, `context.sha ${context.sha} must be a merge commit`)
  await fetchCommitsBetweenBaseHead(baseSHA, headSHA, context)

  core.info(`Cherry-pick the workspace changes onto the head branch`)
  await git.checkout(headSHA)
  if (await git.tryCherryPick(workspaceChangeSHA)) {
    return
  }

  core.info(`Falling back to update the head branch and then cherry-pick the workspace changes onto it`)
  await git.checkout(headSHA)
  const headRef = context.payload.pull_request.head.ref
  const baseRef = context.payload.pull_request.base.ref
  await git.merge(baseSHA, [
    `Merge branch '${baseRef}' into ${headRef}`,
    `Base-branch: ${baseRef}@${baseSHA}`,
    `Head-branch: ${headRef}@${headSHA}`,
    getAutoGeneratedTrailer(context),
  ])
  await git.cherryPick(workspaceChangeSHA)
}

const fetchCommitsBetweenBaseHead = async (baseSHA: string, headSHA: string, context: Context) => {
  for (let depth = 50; depth < 1000; depth += 50) {
    if (await git.canMerge(baseSHA, headSHA)) {
      core.info(`Fetched commits required to merge base and head`)
      return
    }
    await git.fetch({ refs: [baseSHA, headSHA], depth }, context)
  }
}
